# Generated by Django 4.1.2 on 2022-10-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="women.category",
            ),
        ),
    ]
