# Generated by Django 4.1.2 on 2022-10-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0002_women_cat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="women",
            name="photo",
        ),
    ]
