# Generated by Django 4.1.2 on 2022-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0003_remove_women_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="photo",
            field=models.ImageField(default="", upload_to="photos/%Y/%m/%d/"),
        ),
    ]
