# Generated by Django 4.1.2 on 2022-12-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0004_women_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="women",
            options={
                "verbose_name": "Известные женщины",
                "verbose_name_plural": "Известные женщины",
            },
        ),
        migrations.AlterField(
            model_name="women",
            name="photo",
            field=models.ImageField(
                blank=True, default="", upload_to="photos/%Y/%m/%d/"
            ),
        ),
    ]
