# Generated by Django 4.1.2 on 2022-12-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0005_alter_women_options_alter_women_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="women",
            name="cat",
        ),
    ]
