# Generated by Django 4.1.2 on 2022-12-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0007_women_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="slug",
            field=models.SlugField(
                max_length=255, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
