# Generated by Django 4.1.2 on 2022-12-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0009_alter_women_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=255, null=True, unique=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Категория"
            ),
        ),
    ]
