# Generated by Django 4.1.2 on 2022-12-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0010_category_slug_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
