version: '3'

services: 
    db:
      image: postgres:14.3-alpine
      container_name: DB-container
      volumes:
        - postgres_volume:/var/lib/postgresql/data/

      expose:
         - 5432
      environment:          
        - POSTGRES_USER=mih
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=women_db
    
    web:
        build: ./bal-women
        container_name: DJANGO-container
        hostname: web
        
        command: gunicorn drfsite.wsgi:application --bind 0.0.0.0:9000
        
        
        volumes:
          - static_volume:/app/static
        
        expose:
          - 9000     
          
        depends_on: 
          - db 
    nginx:
        build: ./nginx
        container_name: my_nginx 
        hostname: nginx
        volumes:
          - static_volume:/app/static
            
        ports:
          - 8080:80
        depends_on:
          - web   
volumes:
  static_volume:
  postgres_volume:          
  